# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6887886c4fafeeb7eb4e970e7b8c7e2309a04503739a5067159b93dc1dcc442dfc65067d31ddf474609e122580d84993daa26baa5d519da70c0cf9dc5233cb28

test:
  secret_key_base: ed016c4aa5a436fdbfc38cd1dbd89962f07a0e51f058b888c41e9697062240b98fccde1cd3fb7f104f45aecfec7a49de278ca23d0a0a00111aad936c60c079b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
